### ISSUE TITLE
Rewrite to JavaScript

### ISSUE THREAD

**Issue by matthijsmelissen** [matthijsmelissen/qif-converter#2]
It would be cool if we could run the conversion locally in the browser, so users of this tool don't need to trust the server on which it is hosted with their financial data. Therefore, it would be nice if we could create a JavaScript version of the tool.

**Comment by nonbinary** [comment]
It is quite easy, at least on a Linux workstation, to run this script on your own machine. Install a webserver (eg apache/httpd), move the script into your /var/www/html folder, start the webserver, and browse to http://localhost.
