### ISSUE TITLE
Look over thousands separators

### ISSUE THREAD

**Issue by nonbinary** [matthijsmelissen/qif-converter#4]
I experienced some trouble with the seb setup:

I downloaded an xlsx file from SEB, which I opened in LibreOffice.
From here, I exported the csv file.
There was some confusion in the formatting of the xlsx file, which caused some amounts to be typed as: 3,342.00
When the script replaces all commas with dots, the amount turned into 3.342.00, which the script interpreted as 3

After some careful formatting of the cells in LibreOffice, I got around this.
But it might be helpful to have the script catch this incorrect formatting, and it shouldn't be all that difficult.

**Comment by matthijsmelissen** [comment]
Thanks, it seems we did not test properly for numbers larger than 999.

I made some big changes to the script: I moved everything from PHP to Javascript. I would like to test also move the SEB conversion to JavaScript, but I don't have an example file to test if it works. Could you perhaps send me the first couple of lines from an example SEB CSV file? You can reach me at qif@matthijsmelissen.nl.

**Comment by nonbinary** [comment]
I have tested with new files from swedish SEB and Skandia, and they work flawlessly.
