### ISSUE TITLE
Small suggestions for improvements

### ISSUE THREAD

**Issue by Rob--W** [matthijsmelissen/qif-converter#6]
Hi Matthijs, thanks for saving the time of not having to re-invent the wheel. I audited the source code before use, and found some room for improvements:

- index.html references an external script (without [SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity), so the integrity of the file cannot be guaranteed). jQuery is not used, so remove the line that loads jQuery:  
  https://github.com/matthijsmelissen/qif-converter/blob/49ee9da7de6b91e9061776d31ace214a460a7b77/index.html#L5
- This `=` should have been a `==`:  
  https://github.com/matthijsmelissen/qif-converter/blob/49ee9da7de6b91e9061776d31ace214a460a7b77/script.js#L9

The following are not directly accessible through the UI, but they would be broken anyway due to the following issues:

- `$row` and `$fields` are not defined. You should remove `$` and prepend `var fields = {};`:  
   https://github.com/matthijsmelissen/qif-converter/blob/49ee9da7de6b91e9061776d31ace214a460a7b77/script.js#L132-L138
- In the original PHP version, you used `str_replace`, which replaces all occurrences. The `.replace` function in JavaScript only replaces the first occurrence. Use `.replace` with a regular expression and the `g` flag to replace all occurrences, e.g. by using `.replace(/\0/g, '')` , `.replace(/\xA/g, '')` , `.replace(/ /g, '')` , etc. :  
https://github.com/matthijsmelissen/qif-converter/blob/49ee9da7de6b91e9061776d31ace214a460a7b77/script.js#L80-L96

**Comment by matthijsmelissen** [comment]
Thanks, all good points! Implemented this now.
